# Repository settings
repository:
  name: tfunify
  description: "Unified trend-following systems in pure NumPy"
  homepage: https://github.com/diogoribeiro7/tfunify
  topics: trend-following, momentum, cta, quant, timeseries
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: develop

# Branch protection rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test (3.10)"
          - "test (3.11)" 
          - "test (3.12)"
          - "CI / test"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test (3.11)"
          - "CI / test"
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
