# Repository settings
repository:
  name: tfunify
  description: "Unified trend-following systems in pure NumPy"
  homepage: https://github.com/DiogoRibeiro7/tfunify
  topics:
    - trend-following
    - momentum
    - cta
    - quant
    - timeseries
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: develop

# Branch protection rules (classic Branch Protection via settings.yml)
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        checks:
          - context: "CI / test (3.10)"
          - context: "CI / test (3.11)"
          - context: "CI / test (3.12)"
          - context: "CI / integration-test"
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

  - name: develop
    protection:
      required_status_checks:
        strict: true
        checks:
          - context: "CI / test (3.10)"
          - context: "CI / test (3.11)"
          - context: "CI / test (3.12)"
          - context: "CI / integration-test"
      enforce_admins: false
      required_pull_request_reviews: null
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false

