codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 2%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/"
  - "examples/"
  - "docs/"
  - "setup.py"
