name: Release

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main  # Only run releases from main branch

jobs:
  verify-branch:
    name: Verify release is from main branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify tag is on main branch
        run: |
          # Ensure remote refs exist
          git fetch origin +refs/heads/*:refs/remotes/origin/* --tags

          TAG_COMMIT=$(git rev-list -n 1 "$GITHUB_REF")
          echo "Tag commit: $TAG_COMMIT"

          if git merge-base --is-ancestor "$TAG_COMMIT" origin/main; then
            echo "✅ Tag is on main branch"
          else
            echo "❌ Error: Tag is not on main branch"
            exit 1
          fi

          MAIN_COMMIT=$(git rev-parse origin/main)
          echo "Main commit: $MAIN_COMMIT"

          if [ "$TAG_COMMIT" = "$MAIN_COMMIT" ]; then
            echo "✅ Tag points to latest main commit"
          else
            echo "⚠️  Tag is not the latest main commit"
          fi

  test:
    name: Run tests before release
    runs-on: ubuntu-latest
    needs: verify-branch
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Configure Poetry + Install
        run: |
          set -e
          poetry config virtualenvs.prefer-active-python true
          poetry env use "$(python -c 'import sys; print(sys.executable)')"
          poetry install --with dev --no-interaction --no-ansi

      - name: Run linting
        run: |
          poetry run ruff check .
          poetry run ruff format --check .

      - name: Run type checking
        run: poetry run mypy tfunify

      - name: Run unit tests
        run: poetry run pytest --cov=tfunify --cov-report=term-missing --cov-fail-under=80

  test-cli:
    name: Test CLI functionality before release
    runs-on: ubuntu-latest
    needs: verify-branch
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Configure Poetry + Install
        run: |
          set -e
          poetry config virtualenvs.prefer-active-python true
          poetry env use "$(python -c 'import sys; print(sys.executable)')"
          poetry install --no-interaction --no-ansi
          # If numpy is only a main dependency, this suffices.
          # If it's optional, uncomment the next line:
          # poetry run pip install numpy

      - name: Create test data (inside Poetry env)
        run: |
          poetry run python - <<'PY'
          import numpy as np, csv
          np.random.seed(42)
          n = 200
          prices = 100 + np.cumsum(0.01 * np.random.randn(n))
          with open('test_data.csv', 'w', newline='') as f:
              w = csv.writer(f)
              w.writerow(['date', 'close'])
              for i, p in enumerate(prices):
                  w.writerow([f'2023-{(i%12)+1:02d}-{(i%28)+1:02d}', f'{p:.2f}'])
          PY

      - name: Test all CLI commands
        run: |
          poetry run tfu european --csv test_data.csv --span-long 50 --span-short 10
          poetry run tfu american --csv test_data.csv --span-long 50 --span-short 10 --atr-period 20
          poetry run tfu tsmom --csv test_data.csv --L 5 --M 8

      - name: Verify output files exist and are valid (inside Poetry env)
        run: |
          poetry run python - <<'PY'
          import numpy as np, sys
          ok = True
          for system in ['european', 'american', 'tsmom']:
              try:
                  data = np.load(f'{system}_results.npz')
                  print(f'{system}: keys={list(data.keys())}')
                  assert len(data.files) > 0
              except Exception as e:
                  ok = False
                  print(f'Validation failed for {system}: {e}', file=sys.stderr)
          if not ok:
              raise SystemExit(1)
          print('All CLI tests passed!')
          PY

  build-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    needs: [verify-branch, test, test-cli]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"

      - name: Verify version tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Tag version: $TAG_VERSION"
          poetry config virtualenvs.prefer-active-python true
          poetry env use "$(python -c 'import sys; print(sys.executable)')"
          PYPROJECT_VERSION=$(poetry version --short)
          echo "Pyproject version: $PYPROJECT_VERSION"
          if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
            echo "Error: Tag version ($TAG_VERSION) doesn't match pyproject.toml version ($PYPROJECT_VERSION)"
            exit 1
          fi
          echo "Version verification passed!"

      - name: Build package
        run: |
          poetry install --no-root --no-interaction --no-ansi
          poetry build

      - name: Verify build
        run: |
          ls -la dist/
          python - <<'PY'
          import zipfile, os, glob
          wheels = [f for f in os.listdir('dist') if f.endswith('.whl')]
          if not wheels: raise SystemExit('No wheel file found')
          with zipfile.ZipFile(os.path.join('dist', wheels[0]), 'r') as z:
              files = z.namelist()
              print('Wheel contents:')
              for f in sorted(files): print(' ', f)
              if not any(f.startswith('tfunify/') and f.endswith('.py') for f in files):
                  raise SystemExit('No tfunify Python files found in wheel')
          PY

      - name: Test installation from wheel
        run: |
          python -m venv test_env
          source test_env/bin/activate
          pip install --upgrade pip
          pip install dist/*.whl
          python - <<'PY'
          import tfunify, numpy as np
          from tfunify.european import EuropeanTF, EuropeanTFConfig
          print(f'tfunify version: {tfunify.__version__}')
          np.random.seed(42)
          prices = 100 * np.cumprod(1 + 0.01 * np.random.randn(100))
          cfg = EuropeanTFConfig(span_long=20, span_short=5)
          pnl, *_ = EuropeanTF(cfg).run_from_prices(prices)
          print(f'Test run successful, PnL shape: {pnl.shape}')
          PY
          deactivate

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --username __token__ --password "$POETRY_PYPI_TOKEN_PYPI"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this release
            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.

            ## Installation
            ```bash
            # strip the leading 'v' in the tag name
            pip install tfunify==${{ github.ref_name/*v/ }}
            ```
          draft: false
          prerelease: false
